### ISSUE TITLE
Error Not Valid Xdelta3 Patch

### ISSUE THREAD

**Issue by Verdial** [Trixarian/NetherSX2-patch#10]
in version 1.4 there is no problem, 1.5 the problem appears as shown in the picture

![Screenshot_20230905-025521689](https://github.com/Trixarian/NetherSX2-patch/assets/99362544/61a44608-8c2c-400e-aa68-c493a42fb241)

**Comment by Trixarian** [comment]
Apply the xdelta file to a vanilla copy of [AetherSX2 4248](https://cdn.discordapp.com/attachments/1063822057319702621/1138278844474859540/15210-v1.5-4248.apk), not an already patched one

**Comment by Verdial** [comment]
solved thanks
