### ISSUE TITLE
Front Mission 5 Scars of War, Could not load game in the first menu

### ISSUE THREAD

**Issue by arifiyansyah** [Trixarian/NetherSX2-patch#18]
I tried to load my saved game in Front Mission 5, suddenly it forced close

**Comment by Trixarian** [comment]
This is a known bug with this game and later versions of PCSX2 1.7 Nightly Builds (which this emulator is based on). Switch to the Software Renderer before loading the your save and it'll work. https://wiki.pcsx2.net/Front_Mission_5:_Scars_of_the_War#Known_Issues
