### ISSUE TITLE
custom texture loading error

### ISSUE THREAD

**Issue by ValkyrieReika** [Trixarian/NetherSX2-patch#2]
Custom texture uploads are disabled or not working.  Official versions do not have this problem if possible to check

**Comment by Trixarian** [comment]
What do you mean? It seems to be working fine

Without texture pack: 
![Screenshot_2023-08-31-12-09-01-837_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/983358/4ac121af-3c62-4981-ae6b-648062c2dc9f)

With texture pack:
![Screenshot_2023-08-31-12-08-27-044_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/983358/d56fe8a4-1f7d-4f84-9ce3-86be6b68f32b)

**Comment by ValkyrieReika** [comment]
![Screenshot_20230903-233616](https://github.com/Trixarian/NetherSX2-patch/assets/105957496/6bf57e55-bcc9-4dfb-8654-fa5223efc39c)
N
![Screenshot_20230903-233804](https://github.com/Trixarian/NetherSX2-patch/assets/105957496/fb7d7687-2b4e-4282-8c3b-5660811bcaec)
![Screenshot_20230903-234037](https://github.com/Trixarian/NetherSX2-patch/assets/105957496/31881095-d52c-458c-8cfb-a1acb11ab3e5)
![Screenshot_20230903-234140](https://github.com/Trixarian/NetherSX2-patch/assets/105957496/b2e8a048-d634-42f7-ae9d-e95ca2eae9d7)
![Screenshot_20230903-234214](https://github.com/Trixarian/NetherSX2-patch/assets/105957496/51aba56c-087b-4088-868f-98c3b6f43d67)

**Comment by ValkyrieReika** [comment]
The first one is NetherSX2-patch the second one is aethersx2 latest version without ads in which the custom texture loading continues to work

**Comment by Trixarian** [comment]
It works
![Screenshot_2023-09-04-08-26-34-676_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/983358/b3a3d243-ae9c-4c84-9000-e9ee94f343c9)

Is it in the right place and are you using the right settings?
![Screenshot_2023-09-04-08-23-09-954_ru zdevs zarchiver](https://github.com/Trixarian/NetherSX2-patch/assets/983358/01d93719-64ce-43eb-84ac-37a512e40055)
![Screenshot_2023-09-04-08-24-46-024_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/983358/4af3afa5-27ed-446f-acf2-4b8489886ce5)

**Comment by Trixarian** [comment]
Note what it says in the description: [Haunting Ground HD Update 1. 2 (Use PCSX2 v1.7.3519 or older) only PAL](https://www.youtube.com/watch?v=pKzVGkLPldg&t=93s) - for versions [v1.7.3519](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.3519) or Under. Meaning any version of PCSX2 older than November 3rd of last year.

Seems it just an issue with the older texture pack, so the easiest way to fix it would be to just update to [v1.3 of the Texture Pack](https://gbatemp.net/threads/haunting-ground-hd-1-3-texture-pack-by-juanchotexhd-pal-ntsc.611542/). It works fine with NetherSX2
