### ISSUE TITLE
Guitar Hero 3 Lag Fix 

### ISSUE THREAD

**Issue by TheBoxGame** [Trixarian/NetherSX2-patch#21]
Hello, I have a question whether it would be possible to fix the problem with lag in the game. During the game, at some moments the game hangs terribly and is not playable. I first tried it on OpenGL and at the maximum clock speed reduction and at -50 and nothing, then I changed it to Vulcan, apparently something happened, but it didn't help anyway. Could this error be fixed?

**Comment by Trixarian** [comment]
Try Disabling Readbacks under Hardware Download Mode. It's a general performance fix for effects heavy games. If the game is reporting running 100% but dropping frames, the also consider turning off Skip Presenting Duplicate Frames for the game since it may be breaking the Frame Limiter for it
