### ISSUE TITLE
Need for speed carbon 

### ISSUE THREAD

**Issue by Sickb8y** [Trixarian/NetherSX2-patch#25]
Some way to avoid this? 
This problem is only with vulkan in many games

https://github.com/Trixarian/NetherSX2-patch/assets/140640705/988aebdd-8efb-467d-b9e5-0df157f6d9a7

**Comment by Trixarian** [comment]
Use OpenGL for games with that error. The Vulkan Renderer is asking your phone's vulkan driver for a feature that it doesn't support, so it errors out or straight up crashes. This is more common with Mali phones than Snapdragon, and the only work around is to use OpenGL instead

**Comment by Sickb8y** [comment]
Yes, when I have this problem I change to OpenGL to advance in the games, Ty you are the best
