### ISSUE TITLE
Achievements problem

### ISSUE THREAD

**Issue by NuggetFangus** [Trixarian/NetherSX2-patch#31]
When i go to the achievements section, its deactivated and i cant see it, and if i start the game with clean boot, the notification doesnt even appears, but when i start it from a savestate it appears, but still not working

**Comment by NuggetSus** [comment]
Sorry if the way i write looks confusing

**Comment by Trixarian** [comment]
Are you enabling Hardcore Mode or blocking the app from accessing the Internet (which is needed to connect to the RetroAchievements website)?
