### ISSUE TITLE
Metal Gear Solid 3: Subsistence patches doesn't work at all

### ISSUE THREAD

**Issue by ANDRO1D-0502** [Trixarian/NetherSX2-patch#35]
In this game, I tried installing 30 fps and 20:9 patches, but none of them work, and the emulator says that there is no patches enabled. In other games all patches work without problems.

**Comment by Trixarian** [comment]
Did you put it in the cheats folder at Android/data/xyz.aethersx2.android/files/cheats and made sure the filename matches your version of Metal Gear Solid 3: Subsistence's CRC hash with a .pnach at the end? 

You can see the CRC hash for the game by long pressing on it in your Game List, and going to Game Properties, and you'll find it's under Summery

**Comment by ANDRO1D-0502** [comment]
![Screenshot_2024-01-03-08-41-44-897_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/145148075/aec3a264-91d7-4bf7-a1a7-25cf24ee0d6e)
Game doesn't see Force 30 and 60 fps patches only. So could be it's only porblem with fps locker, because 21:9 patch now work?

**Comment by Trixarian** [comment]
You may want to remove the // before either the 60fps or 30fps lines. You don't want to run both at the same time

**Comment by ANDRO1D-0502** [comment]
30 fps lock still doesn't work
![Uploading Screenshot_2024-01-03-12-52-01-677_xyz.aethersx2.android.jpg…]()

**Comment by ANDRO1D-0502** [comment]
![Screenshot_2024-01-03-12-52-01-677_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/145148075/f488b9f2-4214-4ec4-8ea7-d4e0ec17877c)

**Comment by Trixarian** [comment]
// means it's a comment - so it's commented out
It needs to look like:
comment=Force 30 FPS
patch=1,...
patch=1,...
patch=1,...

**Comment by ANDRO1D-0502** [comment]
Oh, thank you, didn't know that i need to remove //. Now all working😄
