### ISSUE TITLE
Issues with the bash script

### ISSUE THREAD

**Issue by SweatyNuN** [Trixarian/NetherSX2-patch#49]
Hiya, noticed your bash script has some small issues. First the chmod command on line 53 has the +x in the wrong place change it to:

chmod +x $p2f/lib/xdelta3

The curl download also seems to fetch a 0 byte file, for downloading its much better to use wget and most people will have that so line 65 can be changed to: 

wget -P "$input_path" -q "https://github.com/Trixarian/NetherSX2-patch/releases/download/0.0/15210-v1.5-4248.apk"

I'd make a PR but I'm really lazy, hope this helps!

**Comment by parkerlreed** [comment]
curl works with -L to follow redirects
