### ISSUE TITLE
Fix Music

### ISSUE THREAD

**Issue by TheBoxGame** [Trixarian/NetherSX2-patch#5]
fix music when loading profile in many games for example in flatout game when you load your profile the music freezes
![Screenshot_2023-09-02-17-37-43-241_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/109180532/ed29a164-4345-4d15-bfb2-ee2cc9e04b67)

**Comment by Trixarian** [comment]
Use the Nearest or Linear Interpolation Modes with the Async Mix Synchronization Mode. Failing that, go back to using TimeStretch. This is beyond the scope of what GameDB fixes can do
