### ISSUE TITLE
Namco System 246/256 support

### ISSUE THREAD

**Issue by gtapcfan** [Trixarian/NetherSX2-patch#50]
I was wondering if it's possible for future updates? Although the Sys246 bios is booting at the Emulator (except for Sys256 bios), i have a Tekken 4 dongle converted into a .ps2 memory card file and got the ISO. The only thing is that i only stuck at "Boot Program Error: Boot file is Not Right"

(Because the Namco System 2x6 is a PS2 with a powerful GPU)

**Comment by Trixarian** [comment]
I'm aware that the 246 bios can be booted and some of the MagicGate can be emulated, but there are several issues that block further progress like the keys that are now unobtainable. It's unlikely to be a feature that PCSX2 will implemented (especially after the whole Yuzu mess recently involving keys), and as such it's not something we will be able to inherit in future version of NetherSX2
