### ISSUE TITLE
Failed to Open Path on Android 12

### ISSUE THREAD

**Issue by Dennis12345678901** [Trixarian/NetherSX2-patch#55]
I can't add games on Android 12, I get the error "Failed to start ACTION_OPEN_Document_TREE intent." Is there a fix for this?

**Comment by Trixarian** [comment]
Yes, use a folder outside of system protected folders to store your games. If you try to have it inside the Downloads or Android folders, it'll give you this error since they're system protected. I use a folder named Roms with a PS2 folder inside it to store my games myself and it works fine

**Comment by Dennis12345678901** [comment]
Hello. 
Creating a new folder is not the problem, but rather that I can't select any folder within Neather. The message "Failed to Start..." appears immediately when I click on "Add game directory". So the question is how can I navigate to the ROMs within Neather?




Am Samstag, Mai 4, 2024, 3:25 PM schrieb Trixarian ***@***.***>:




Yes, use a folder outside of system protected folders to store your games. If you try to have it inside the Downloads or Android folders, it'll give you this error since they're system protected. I use a folder named Roms with a PS2 folder inside it to store my games myself and it works fine
