### ISSUE TITLE
Build Process

### ISSUE THREAD

**Issue by Tuxino** [Trixarian/NetherSX2-patch#58]
I run the build-nethersx2.bat from the NetherSX2-builder.zip and it downloads and patches the APK. 

Then I copy the 15210-v1.5-4248-noads.apk from the PatchedAPK folder to my device and install.

What I am noticing is that there are still ads in the app and RetroAchievement notifications are still broken (I got the achievement but no notification on screen)

Have I patched it correctly? 

My device is Android 14 (POCO X6 PRO)

Thanks

**Comment by Tuxino** [comment]
As a workaround, I did the patching on my device using UniPatcher which worked fine. I can no longer see the ads in app

**Comment by Trixarian** [comment]
I suspect that AetherSX2 was still installed when you tried to install NetherSX2, which made it fail. Previous versions of AetherSX2 needs to be uninstalled for NetherSX2 to properly install itself. It's one of the annoying issues with NetherSX2 currently
