### ISSUE TITLE
Black Lines Games 

### ISSUE THREAD

**Issue by TheBoxGame** [Trixarian/NetherSX2-patch#6]
hello, I have a question if it would be possible to fix the problem with black lines in some games but to increase the resolution to, for example, x2 because if it is x1, there are no lines, for example in flatout
![Screenshot_2023-09-03-07-14-55-241_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/109180532/66066f81-9280-4d93-8b91-db5238a4c7c0)
![Screenshot_2023-09-03-07-14-35-444_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/109180532/5a81033b-80e2-4d83-8e48-f2d2042bb841)

**Comment by Trixarian** [comment]
If there's a setting that eliminates them, then I can add it to the GameDB. Looking at the (sparse) wiki entries, there doesn't seem to be a definite fix for it: [FlatOut](https://wiki.pcsx2.net/FlatOut) & [FlatOut 2](https://wiki.pcsx2.net/FlatOut_2)

**Comment by TheBoxGame** [comment]
![IMG_20230903_110239](https://github.com/Trixarian/NetherSX2-patch/assets/109180532/61d5f387-98d4-4fcd-a476-cf9d4f404d36)

**Comment by TheBoxGame** [comment]
there is no black line after using this option
