### ISSUE TITLE
Can you add some cheat or texture skin mod button layout

### ISSUE THREAD

**Issue by Ottorock** [Trixarian/NetherSX2-patch#62]
For let’s say PS1 - PS5 OG Xbox - Series S Or X NGC - NS Skin Mod Button Laylout

**Comment by Trixarian** [comment]
It is possible to add your own theme by decompiling the apk, changing the png files use for the buttons and then recompiling the apk. I provide the tools for it within the decomp folder of this repository if you're willing to mess with it. I would like to add more layouts, but the current interation of NetherSX2 doesn't make it easy to change the buttons on the fly

This may be a feature in the future once we rebuild NetherSX2 from scratch

**Comment by Ottorock** [comment]
Thank You 😎
