### ISSUE TITLE
Colin Macrea Rally 2005 Graphics Fix

### ISSUE THREAD

**Issue by TheBoxGame** [Trixarian/NetherSX2-patch#7]
hello, I have a question if it would be possible to fix the problem with the graphics in Colin Macrea Rally 2005. My point is that after switching to software, graphics and clouds work normally but hang, and after switching to OpenGL and Vulcan, the sky is gray, but the game runs slowly .

**Comment by TheBoxGame** [comment]
![Uploading Screenshot_2023-09-03-11-54-39-720_xyz.aethersx2.android.jpg…]()

**Comment by TheBoxGame** [comment]
![Screenshot_2023-09-03-11-54-39-720_xyz aethersx2 android](https://github.com/Trixarian/NetherSX2-patch/assets/109180532/bafdc9f0-0656-413c-a27b-ed91cb2db697)

**Comment by Trixarian** [comment]
This game has issues. Even applying the two fixes for it still produces colours that are off. We can run it now (as of the coming 1.7), but it's still going to look
