### ISSUE TITLE
UI Trouble

### ISSUE THREAD

**Issue by MistyPaws** [Trixarian/NetherSX2-patch#77]
Please return the "old UI interface", because in a "new" I can't see the D-Pad, it becomes transparent on my phone. Old UI was better, it had shown all buttons properly.

![IMG_20240607_003245](https://github.com/Trixarian/NetherSX2-patch/assets/171984797/74f347d9-b0cd-4781-b8f0-6ed38c929cd1)

![IMG_20240607_003354](https://github.com/Trixarian/NetherSX2-patch/assets/171984797/0e6e5f87-f248-4e10-b945-4f0aba0466a1)

**Comment by Trixarian** [comment]
I don't even know how you only set the D-Pad's opacity to 0%
