### ISSUE TITLE
My patched version has a virus ?

### ISSUE THREAD

**Issue by GrpX** [Trixarian/NetherSX2-patch#80]
I followed the steps for the Android version and when I get the patch, I uploaded it to VirusTotal and it showed me "Kingsoft
Win32.Troj.Admob.a" 

Should I install it anyways?

![Screenshot_20240610_013045_edit_95218225641279](https://github.com/Trixarian/NetherSX2-patch/assets/172240840/c6876dfe-be50-4efb-bb6f-a4ad6a9451ee)

**Comment by Trixarian** [comment]
It's a false positive by Kingsoft, which ironically is known for their [ad driven malware](https://www.malwarebytes.com/blog/detections/pup-optional-kingsoft)
Generally if something comes up as clean on every list on VirusTotal except one or two obscure ones, it's safe to assume that the exceptions are false positives
